version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:80"]
      - ADMIN_USERNAME=Eliejosuevargas01
      - ADMIN_PASSWORD=280108

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend